# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: engage@kbase.us
author_name: KBase
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: berdl-task-browser
project_short_description: A JupyterLab extension for browsing task data
python_name: berdl_task_browser
repository: https://github.com/BERDataLakehouse/berdl_task_browser
test: true

